[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "puzzle1"
path = "src/Puzzle1.rs"

[[bin]]
name = "puzzle2"
path = "src/Puzzle2.rs"

[[bin]]
name = "puzzle3"
path = "src/Puzzle3.rs"

[[bin]]
name = "puzzle4"
path = "src/Puzzle4.rs"

[[bin]]
name = "puzzle5"
path = "src/Puzzle5.rs"

[[bin]]
name = "puzzle6"
path = "src/Puzzle6.rs"

[[bin]]
name = "puzzle7"
path = "src/Puzzle7.rs"

[[bin]]
name = "puzzle8"
path = "src/Puzzle8.rs"

[[bin]]
name = "puzzle9"
path = "src/Puzzle9.rs"

[[bin]]
name = "puzzle10"
path = "src/Puzzle10.rs"

[[bin]]
name = "puzzle11"
path = "src/Puzzle11.rs"

[[bin]]
name = "puzzle12"
path = "src/Puzzle12.rs"

[[bin]]
name = "puzzle13"
path = "src/Puzzle13.rs"

[[bin]]
name = "puzzle14"
path = "src/Puzzle14.rs"